### ISSUE TITLE
xcat python3.6 not work 

### ISSUE THREAD

**Issue by lacroutelacroute** [orf/xcat#16]
i have installed python 3.6.1
into separated directory
i have download from git correspond xcat version python 3.6

i encouter the fatal error
:~$ sudo /usr/local/python-3.6.1/bin/python3 /usr/local/bin/xcat
Traceback (most recent call last):
  File "/usr/local/bin/xcat", line 11, in <module>
    load_entry_point('xcat==0.9', 'console_scripts', 'xcat')()
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/xcat-0.9-py3.6.egg/xcat/cli.py", line 19, in <module>
  File "/usr/local/python-3.6.1/lib/python3.6/site-packages/xcat-0.9-py3.6.egg/xcat/algorithms.py", line 5, in <module>
ModuleNotFoundError: No module named 'xcat.xpath'

I tried with pip3.6 the option --upgrade of pip without more success

**Comment by lacroutelacroute** [comment]
I tried all versions with yes or no install pip in any case it does not work

**Comment by jcortescen** [comment]
I have this same issue, so I guess right now neither 3.6 nor master are working... It'd be awesome if we could get a fix, this is such a great and useful tool

**Comment by orf** [comment]
Hey @jcortescen, thanks for the kind words. Yes, the current master branch is broken on Python 3.6 and I have not kept up maintenance. I have a complete re-write of the application that *does* function on Python 3.6 here: https://github.com/orf/xcat/tree/3.6-redesign-wtf

Please give that a go if you are able. It is currently lacking authentication and new documentation which is the reason I have not released it yet.

Apologies for the delay!

**Comment by jcortescen** [comment]
I did try the 3.6 -redesign-wtf, but I'm getting the same error as OP (ModuleNotFoundError: No module named 'xcat.xpath').

Any ideas?

**Comment by orf** [comment]
Hi @jcortescen 
I've done a fair bit of work tonight to bring the new version of xcat up to date. If you're still interested the `3.6` branch should be ready and working, I've even added some travis CI tests!

I've also fixed up the java example app here: https://github.com/orf/xcat_app

I just need to re-write the documentation and flesh out a few of the `shell` tests and I will merge this into master. Sorry for the delay and the frustration!
