### ISSUE TITLE
Python3.5 with xcat-3.6-redesign-wtf does not work

### ISSUE THREAD

**Issue by anhkhoa14592** [orf/xcat#21]
Hi, 

I've tried to use Xcat with Python3.5 and 3.6 but it doesn't work. I've downloaded the  xcat-3.6-redesign-wtf and run with python3.5 but there are following error:

Traceback (most recent call last):
  File "C:\Python35\Scripts\xcat-script.py", line 9, in <module>
    load_entry_point('xcat==0.9', 'console_scripts', 'xcat')()
  File "C:\Python35\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python35\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "C:\Python35\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
    return self.resolve()
  File "C:\Python35\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python35\lib\site-packages\xcat-0.9-py3.5.egg\xcat\cli.py", line 28, in <module>
  File "C:\Python35\lib\site-packages\aiohttp-2.3.10-py3.5.egg\aiohttp\__init__.py", line 6, in <module>
  File "C:\Python35\lib\site-packages\aiohttp-2.3.10-py3.5.egg\aiohttp\client.py", line 13, in <module>
  File "C:\Python35\lib\site-packages\yarl-1.2.4-py3.5.egg\yarl\__init__.py", line 11, in <module>
  File "C:\Python35\lib\site-packages\yarl-1.2.4-py3.5.egg\yarl\quoting.py", line 3, in <module>
ImportError: cannot import name 'TYPE_CHECKING'

**Comment by orf** [comment]
I'm aware of this and I'm working on it. I've redesigned the internals, current master is working-ish but still needs work (OOB and shell).

**Comment by orf** [comment]
Hello,
I've just released `xcat` 1.0 on pypi 🎉 . I've redesigned the CLI and it now all works. Please see the updated README for information.

I'm working on the documentation now. Please open an issue if you run into trouble.
